### ISSUE TITLE
Broken in 10.0

### ISSUE THREAD

**Issue by NagisaStreams** [Kiatra/EpicMusicPlayer#3]
Loved this addon, but seems to not work in Dragonflight. The little icon still appears and I can change volume but main UI seems to be broken. I have attached the error as a file as well as a screenshot of what it looks like when opened. 
![EpicMusicPlayer error](https://user-images.githubusercontent.com/23243364/202842854-2190d801-a93f-446d-9a96-34fec23bf04f.jpg)
[EpicMusicPlayer error print.txt](https://github.com/Kiatra/EpicMusicPlayer/files/10046516/EpicMusicPlayer.error.print.txt)

**Comment by Kiatra** [comment]
Fixed in 7.8

**Comment by NagisaStreams** [comment]
> Fixed in 7.8

Hi thank you for fixing the issues, is there any chance that the Dragonflight music will be added as a tab?

**Comment by NagisaStreams** [comment]
Sounds great thank you :)
